# Created the function to validate the user question so that 
# only question with correct validations should get send to the LLM

import re

MAX_QUESTION_LENGTH = 1000

def validate_question_length(question: str) -> None:
    if not isinstance(question, str):
        raise ValueError("question must be a string")

    question = question.strip()

    if not question:
        raise ValueError("Question cannot be empty")

    if len(question) > MAX_QUESTION_LENGTH:
        raise ValueError(
            f"Question is too long. Maximum allowed length is "
            f"{MAX_QUESTION_LENGTH} characters."
        )


def detect_malicious_input(question: str) -> None:
    """
    Basic first-pass detection for obvious SQL injection attempts
    in the user's natural-language question.

    This is NOT the main security layer.
    SQL generated by the LLM must still pass security.validate_sql().
    """

    suspicious_patterns = [
        r"\bDROP\s+TABLE\b",
        r"\bDROP\s+DATABASE\b",
        r"\bDELETE\s+FROM\b",
        r"\bTRUNCATE\s+TABLE\b",
        r"\bALTER\s+TABLE\b",
        r"\bINSERT\s+INTO\b",
        r"\bUPDATE\s+\w+\s+SET\b",
        r"--",
        r"/\*",
        r"\*/",
        r";\s*(DROP|DELETE|INSERT|UPDATE|ALTER|TRUNCATE|CREATE|GRANT|REVOKE)\b",
    ]

    for pattern in suspicious_patterns:
        if re.search(pattern, question, re.IGNORECASE):
            raise ValueError(
                "Potentially malicious input detected."
            )



def validate_question(question: str) -> str:

    if not isinstance(question, str):
        raise ValueError("Question must be string")

    cleaned_question = question.strip()

    validate_question_length(cleaned_question)
    detect_malicious_input(cleaned_question)

    return cleaned_question
